### ISSUE TITLE
Re-INVITE breaks jbuf

### ISSUE THREAD

**Issue by YuukiHogo** [baresip/baresip#1431]
After re-invite RTP packet seqno can be reseted. Because of this, jbuf_put() starts to reject RTP packets with ETIMEDOUT.

Reproduced with v.1.0.0, but did not found any significant change in related code in master.

**Comment by cspiel1** [comment]
A re-INVITE is in SIP and RTP is not directly coupled.

Talking about RTP:
The `jb->seq_get` is set to zero if the SSRC changes. Otherwise it should not be set to zero.

A re-INVITE should allocate new streams. This includes also new jbuf instances. They will start with `seq_get=0`.

Pleas could you reproduce with master HEAD and give us details about your configuration?!
- Can you reproduce this with a peer-to-peer call from baresip to baresip?
- Or which peer do you use?

**Comment by YuukiHogo** [comment]
I did found source if issue - it is bug in asterisk. Peer changed SSRC, but asterisk is not.
