### ISSUE TITLE
audio source should be started only when needed

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#1659]
Currently audio source is started for a call even if the call does not send audio.  This makes such calls to fail, when the host where baresip is running does not have access to audio source device.

See https://groups.google.com/g/baresip/c/VeNgdNzrkbQ for further discussion.

**Comment by cspiel1** [comment]
I will have a look on this.
Note: The link to google group is wrong.

**Comment by juha-h** [comment]
Thanks, now the link works.

This is not just Android specific issue.  For example, there could be a device, such as bump at gas station, that speaks to customer when customer presses digits on the keypad.  Digits are sent as INFO messages and there is no microphone in the device.

**Comment by cspiel1** [comment]
I also often came to this point or question, if it would be possible to postpone the allocation of the audio source. Since commit e80b7863ddabe9fda93845738a4760525b4f2676 in November we have the function `call_streams_alloc()` where we already postpone the allocation after the DNS request for the call (if there has to be done one).
We have to be careful because everything we change here influences the audio quality at the beginning of the call. E.g. Audio buffer underruns can be the consequence.

Soon I want to propose some improvements for the audio processing. Tiny chances how jbuf and aubuf is used for the decoding thread which should avoid audio underruns. Then we could also try to move the allocation of audio_src and playback after the SDP was negotiated.

**Comment by juha-h** [comment]
At UAC it is not necessary to wait until negotiation is done if SDP in offer has a=recvonly.

**Comment by alfredh** [comment]
in the old days, the audio source was started as early as possible to speed up call setup
times on the first iPhone, this was around 2011 I think, it took around 3-4 seconds to open the
audio recording.

today the best approach should be:

1. wait for signaling to complete
2. open audio source/playback depending on sendrecv direction

**Comment by cspiel1** [comment]
Okay. The function `call_streams_alloc()` could be called later. Will try to create a PR soon. Or maybe someone else wants to do this.

I plan do create a PR with improved jbuf, aubuf and RTP socket handling. This should reduce audio underruns at the beginning of the call. But this could also be done afterwards.

**Comment by sreimers** [comment]
> I plan do create a PR with improved jbuf, aubuf and RTP socket handling.

Some optimization I have on my roadmap: aubuf can use auframe->timestamp for playout adaption (jitter and reorder handling), and we can drop the separate buffer (jbuf). Besides the advantage of lower latency and easier handling, we can add silence suppression (dropping silence frames) or resampling to increase/decrease the buffer.

**Comment by juha-h** [comment]
I'm not in a hurry with this.  Take your time with the PR.

**Comment by cspiel1** [comment]
@sreimers This is interesting. I did a lot of studies about an adaptive jitter buffer. What I always thought is that the RTP packets have to be taken into account in order to implement an adaptive jitter buffer. But maybe all you need are the timestamps (RTP and real time of arrival) in order to compute a reliable jitter. So you plan something like this?

```
[ RTP socket] --> [decoder] --> [adaptive aubuf] --> [speaker]
```
Your right with the benefits.

**Comment by sreimers** [comment]
@cspiel1 Yes that's what I have in mind. I will add a PR today for `aubuf_sort_auframe()`, so we can reorder `aubuf->afl` by `auframe->timestamp` if necessary (RTP timestamp too old).

**Comment by alfredh** [comment]
should we move this item to the roadmap ?

it is not a urgent bug IMO, it is more of an optimalisation.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> should we move this item to the roadmap ?
> 
> it is not a urgent bug IMO, it is more of an optimalisation.

OK with me to move this to roadmap although it is not just an
optimization, since it is impossible to make calls if audio source is
not available.

**Comment by alfredh** [comment]
you can also disable the audio source if you dont want to use it:

```
audio_source    none,none
```

Baresip is first and foremost a full duplex two-way SIP client, which assumes
that both audio source + player is available.
