### ISSUE TITLE
Video is Pausing while receiving I frame

### ISSUE THREAD

**Issue by sreimers** [baresip/baresip#1983]
> Yeah I've tried with avformat module for H264 file parse and avcodec for packetization. No local changes in baresip latest code. Local rendering seems to be fine but in streaming I can still see  the frame jerk.

_Originally posted by @bala-t in https://github.com/baresip/baresip/discussions/1967#discussioncomment-3187758_

**Comment by alfredh** [comment]
@bala-t

looks like the problem could be slow hardware. Could you please share some info about
your platform/OS ?

please upgrade to latest version (v2.6.0) or GIT HEAD.

if the problem is slow decoding time, please do some profiling of the decoder.
this can be done by sampling the time using `tmr_jiffies_usec` and
calculate the delta before and after a function call.

**Comment by alfredh** [comment]
lets continue the discussion in Discussions ...
