### ISSUE TITLE
X11 window is not closed

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#2074]
X11 window is not closed when `call: got INVITE (SDP Offer) audio-video: sendrecv-inactive` event  is received

**Comment by juha-h** [comment]
I made an experiment by adding this piece of code to `call/sipsess_offer_handler()`:
```
if (vrdir == SDP_INACTIVE)
		video_update(call->video, call->peer_uri);
```
That caused close of X11 window, but I have no clue what is the proper fix, which would need to take care also the case when videodir is sendonly.

**Comment by alfredh** [comment]
if the session goes from Audio+Video to Audio only, it seems natural that the X11 windows is closed.

please take a look at `video_update` it should answer your questions regarding RECVONLY etc.

**Comment by juha-h** [comment]
So would it be OK to always call `video_update(call->video, call->peer_uri);` in `call/sipsess_offer_handler()` or only if some condition is met?

**Comment by alfredh** [comment]
I dont remember the details of how this was implemented.

Perhaps @cspiel1 can give some guidance ?

**Comment by juha-h** [comment]
Instead of changing call/sipsess_offer_handler(), calling video_update in menu.c/ ua_event_handler() works too:
```
	case UA_EVENT_CALL_REMOTE_SDP:
		if (!str_cmp(prm, "answer") &&
				call_state(call) == CALL_STATE_ESTABLISHED)
			menu_selcall(call);
		video_update(call_video(call), call_peeruri(call));
		break;
```
That change should be safe to make.

**Comment by alfredh** [comment]
Great, that looks fine to me

Do you want to create a PR for this issue ?

**Comment by juha-h** [comment]
Done in https://github.com/baresip/baresip/pull/2113.

**Comment by cspiel1** [comment]
> I dont remember the details of how this was implemented.
> 
> Perhaps @cspiel1 can give some guidance ?

Sorry, didn't realize this. I will have a look on this. I suggest, that the solution should work also without `menu`.

**Comment by cspiel1** [comment]
Yes, the fix should be done in call.c. Reason when the remote wants to switch off video there these cases:
incoming SDP offer --> `sipsess_offer_handler()` is called --> `update_media()` is called
incoming SDP answer --> `sipsess_answer_handler()` is called --> `update_media()` is called
SIP 183 Session Progress is received --> `sipsess_progr_handler()` is called --> `update_media()` is called or `call_stream_stop()` which calls `video_stop()`

So, `sipsess_progr_handler()` has already a special video close solution. Maybe not the best. I have to discuss this with @maximilianfridrich . He made the 100rel extension.

**Comment by maximilianfridrich** [comment]
From what I understand, after talking to @cspiel1, it sounds like the root of the issue in this scenario (and maybe others) is that `video_update()` is not called in `call.c:update_media()` when it should be called. A possible solution could be to remove the check whether the **video** stream is ready (not audio) because `video_update` looks like it handles those cases correctly and calls `video_stop_source()` and `video_stop_display` as it should.

We have also identified improvements that we can make in the handling of SDP answers, especially in regards to early media. Those should be unrelated to this issue though.

**Comment by cspiel1** [comment]
- So not directly related, but also relevant: When `update_media()` should be called? Answer: We think only in the offer and answer handler. Next question: When offer/answer handler should be called from `re`? We think if SDP offer/answer is received. We will open a PR for a discussion and for testing soon.
- Directly related to this issue: `update_media()` is called very often, sometimes twice during processing of incoming 183 Session Progress. Stopping of the video source and playback does not work because of this commit:
```
commit fb99976031e63bb1a53d9213dd6b185cf43639a0
Author: Alfred E. Heggestad <alfred.heggestad@gmail.com>
Date:   Mon Jul 15 13:02:51 2019 +0200

    webrtc interop (#756)
```
More concretely this `if` statement is the problem:
```c
	if (stream_is_ready(video_strm(call->video))) {
		err |= video_update(call->video, call->peer_uri);
	}
```

The function `update_media()` does not an update, it does only a start.

Another thing we realized is that `update_audio()` and `video_update()`, both called in `update_media()` are doing different things. --> This should also be investigated furhter.

**Comment by cspiel1** [comment]
The third point:
`video_update()` sets the codecs and starts video, whereas `update_audio()` only sets the codecs. The audio is started somewhere else and it also doesn't differentiate between sendonly/recvonly/sendrecv. --> Another PR.

**Comment by juha-h** [comment]
Closing this, since the issue has been fixed.
