### ISSUE TITLE
Android app doesn't start video stream after these 2 commits

### ISSUE THREAD

**Issue by KORuL** [baresip/baresip#2248]
I have built baresip for an android project. But I have to revert 2 commits each time, which break the connection.
If I reverse these 2 commits - everything works fine(but throuth mobile network), but as soon as I apply first of these commits - the sound from the call goes on, but the video stream does not start. If second - connection timout
https://github.com/baresip/baresip/commit/c276dcc8c68c513d085e9ce4fee992933731f5a8
https://github.com/baresip/baresip/commit/6bcc376d3c83983a66df60b81c504c16a6951294

I have to fork and cherry pick 2 of my commits to revert your changes
https://github.com/KORuL/baresip/tree/broke_android_call
https://github.com/KORuL/baresip/tree/revert_nat

Also your NAT piercing commit doesn't work, the turn server doesn't flow. The connection to the turn server is established, but the flow does not start

**Comment by juha-h** [comment]
You need to use baresip-studio project if you want to discuss issues related to it.  But it is only possible for me to try to solve issues that appear when latest version of baresip app is installed from F-Droid or Play Store.  Otherwise the issue may be related your own modifications or build process.

See https://github.com/juha-h/baresip-studio/issues/290#issuecomment-1277910485.  I cannot reproduce this issue.

**Comment by alfredh** [comment]
We dont support custom applications in this forum, please use Discussions or Mailing list for that.

If there is a bug, please reproduce the bug with the vanilla baresip from git HEAD and
no local changes. Please supply the required information and open a new ticket.
