### ISSUE TITLE
Wishlist Item: Prefer IPv6 if Dualstack is Available

### ISSUE THREAD

**Issue by muellert** [baresip/baresip#2793]
I am sitting behind a home router that gives me IPv4 and IPv6. By default, my Android 13 seems to prefer IPv4. This results in the phone registering no problem, but I can't make a phone call. Only if I force baresip to use IPv6 only, can I make a phone call. I would like baresip to try IPv6 first, no matter what, and only fall back if that fails, so I can forget about what kind of network I'm in (various different ones) and just leave it set to "automatic".

**Comment by alfredh** [comment]
Please include relevant info:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues

**Comment by muellert** [comment]
Sorry. I am using the APK downloaded from FDroid, version 59.0.3 on a mobile that is running LineageOS. Let me see how to produce logs.

**Comment by alfredh** [comment]
https://github.com/juha-h/baresip-studio

please use this project

**Comment by alfredh** [comment]
@juha-h

**Comment by juha-h** [comment]
If I remember correctly, there is currently no config option that would allow preferring ipv4 or ipv6 when both are available.  It is only possible to specify, which address family or both is used.

**Comment by juha-h** [comment]
Config option `net_af` was not documented.  I added it: https://github.com/baresip/baresip/wiki/Configuration#net_af. Looks like what you are asking is not available.

**Comment by juha-h** [comment]
As @alfredh wrote, you have to provide more information about the issue.  For example, what do you mean by "making phone call".  Is INVITE accepted, but audio does not work or what?  You need to provide SIP trace.

But I don't think that this is a baresip issue. If your provided requires you to use IPv6, they should configure their domain names in DNS so that  only IPv6 addresses are returned or you should configure outbound proxy using IPv6 address.  But if the provider accepts both and IPv6 addresses, then it may be an issue with your router configuration.

**Comment by alfredh** [comment]
he is using APK so wrong project.
